name: Cypress Tests

on:
  push:
    branches:
      - master
    schedule:
      - cron: "0 12 * * 1,2,3,4,5"
  pull_request:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run --spec "cypress/e2e/pagina_EAD.cy.js"
